### ISSUE TITLE
New Project Proposal - Java Client library for Ethereum

### ISSUE THREAD

**Issue by splix** [ethereumproject/volunteer#22]
A Java library to operate through Ethereum JSON RPC

Java is standard de facto for corp and fintech development, if we want to have clients from big firms it's extremely important to provide full Java support for them (and EthereumJ is not a solution). 

We need flexible client that can connect to Parity and Geth:
 * get any information and convert to Java native structures
 * send transactions 
 * operate contracts 
 * subscribe to blockchain events

I have experience with connecting Java apps to Ethereum and I can easily develop this library. But I will appreciate any help, as I have limited time. I need help with writing documentation and examples. And also we need a good name for this project.

If everybody agree that it's a good idea I can start with this project. Let's discuss

**Comment by whatisgravity** [comment]
For clarification, you are proposing a API Wrapper for both the existing RPC and IPC client in Java? As opposed to the EthereumJ which is a full client implementation. 

I think it is a good idea, and fairly small project compared to a full client. On a similar subject, is EthereumJ implementing a light client yet?

**Comment by splix** [comment]
Yes, API wrapper, a low level around JSON RPC, and a high level on top of it for interacting with contracts.

EthereumJ is a full client implementation, people can probably use it as embedded node, I even think it's EF goal for this project. But it's too heavyweight solution.

**Comment by whatisgravity** [comment]
I think it is a great idea, I believe it would find a lot of use.

**Comment by splix** [comment]
I can start this project this weekend.

Any suggestions how to name this project?

**Comment by ericsomdahl** [comment]
I would like to help with coding too.

One of the most common criticisms this project gets is that it is just a cut&paste.  New code being added should be named in a way that marks it clearly as ETC in origin.

How about 
jetcrpc
j-etc-rpc
jclassic-rpc
etc-rpc4j
those are all pretty business-like.  Maybe there are some crazier ideas...

**Comment by whatisgravity** [comment]
Putting the license as GPL and complaining about "copying and pasting" like it is a bad thing shows a massive gap in knowledge on the purpose of the GPL license. It is literally to guarantee the right to copy, modify, and redistribute that software always remains and that guarantee remains with all derivatives.



Ethereum Classic community is doing an amazing job considering it is purely a volunteer effort that emerged organically and formed an actual decentralized development initiative. 

1. Organize a decentralized community development initiative primarily with strangers, I'm glad to have met you all, it has been wonderful
2. Volunteer developers are having to familiarize ourselves with large projects.
3. Familiarize ourselves with all relevant scientific articles relating to this project
4. Provide thoughtful responses to repeated poor arguments from trolls, so ETC community members without a wide lens on the project are not tricked
5. Merge updates from upstream, while maintain backwards compatibility with eth/62 and the original chain. Now I'm amending the proposed client restoration to properly support a fork object to allow ETC clients to easily use both sides of any network split bifurcation.
6. Setup infrastructure needed to develop in a dedicated secure environment capable of testing a variety of builds.
7.  Work to use gitian to provide more secure builds
8.  Deal with EF developers trying and failing to bullying various ETC by completely overstating their expertise on GPL, and repeatedly making in factual and avoiding any attempt at resolution.
9. Building relationships with experts both in academia and important developers in the cryptocurrency sphere.

And personally, I have also been balancing this with my other ETC projects like the decentralized peer reviewed scientific journal on network science and the articles I'm preparing for submission, building https://github.com/Anastomosis and contributing to the other open source projects I volunteer on. 

---

We have made massive progress, we could have made more given different conditions but overall we have laid a lot of ground work, it is difficult to see exactly what potential our community has, but I can tell you form my experience with talking to different members, it is filled with a **diverse** decentralized group of intelligent, well spoken, reasonable people located all around the world.

If we keep this up, succeed in establishing a multisig wallet to store donations, I believe more like minded developers will follow. The

**Comment by ericsomdahl** [comment]
@splix this project should be very straight-forward.  The big question in my mind is how to treat the domain objects.  Are you of a mind to use JSON-like Map<String, Object> structures or a declared set of strictly-typed domain classes?

I suspect ethereumJ probably already has spec'd the domain objects -- the path of least resistance would be to start from there.

**Comment by splix** [comment]
@ericsomdahl I'm not a big fan of names with `xxxx4j` or `xxxx4java`, like it was popular 15 years ago :) and I don't think name should indicate that it's written by classic team, as we're writing lib that can be used for any of ethereum node and chain, so project name is not the best place for politics imho. `org.ethereumclassic.` package is enough to stand for itself :)

We need something simple and clean for a name, maybe with using _ether_. I see following words as a part of or consonant to project name:

* ether
* connect / connector / bridge
* client
* contract
* commit / commitment
* remote

I like making up fictitious names for a projects, or playing with related words. Imho name should describe the project, but something easy to remember, to pronounce and to google. But nothing comes to mind at this moment.

I'm planing to use strictly typed domains classes. My idea to provide few layers of control, layer by layer, from low level RPC to hight level control of groups of related structures and contract execution. Support both Geth and Parity, with all extended methods, and for every chain. Going to make it Async First. 

There is one important question left, I've not decided yet which java version to use. Java7 is still used by some platform, including Android. And there is nothing imho that requires Java8. I will probably start with Java7, and later we'll figure it out.

**Comment by splix** [comment]
https://github.com/ethereumproject/etherjar
