### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/Volunteer#6]
It is desirable to merge this organization with the ethereumclassic namespace. Unfortunately my work started before I knew about ethereumclassic but the name has been decided and for consistency it may be better to exist under a single organization. 

For go-ethereum this task will require a few hours invested. 

Are there any other projects that require significant amounts of time to migrate to a different repository name space? If we plan for the move it could be a very smooth process but I need others to weigh in on how much additional work would be created by the movement.

**Comment by matthewjamesr** [comment]
Are we dedicated at this point to the namespace move? If so I will initialized the blockexplorer ports over there once I receive a membership access.

**Comment by whatisgravity** [comment]
Sorry, I think this post may be confusing, this was to plan migration, I need to collect information to guage if a manual migration would be preferable over simply deleting the other organization and changing the name of this organization, then updating all require projects. I want to do this in one step. 

In the meantime, simply use this organization, and I will handle the name space migration, I don't think the name space migration is important enough to interfere with pushing development forward. 

You can use this to note if your project requires major changes if the name space changes.

**Comment by bart-w0** [comment]
No major changes required for EthereumJ
